<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nacos_grpc_service.proto

namespace Nacos\Grpc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Payload</code>
 */
class Payload extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Metadata metadata = 2;</code>
     */
    protected $metadata = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Any body = 3;</code>
     */
    protected $body = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nacos\Grpc\Proto\Metadata $metadata
     *     @type \Google\Protobuf\Any $body
     * }
     */
    public function __construct($data = NULL) {
        \Nacos\Grpc\GPBMetadata\NacosGrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Metadata metadata = 2;</code>
     * @return \Nacos\Grpc\Proto\Metadata|null
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    public function hasMetadata()
    {
        return isset($this->metadata);
    }

    public function clearMetadata()
    {
        unset($this->metadata);
    }

    /**
     * Generated from protobuf field <code>.Metadata metadata = 2;</code>
     * @param \Nacos\Grpc\Proto\Metadata $var
     * @return $this
     */
    public function setMetadata(\Nacos\Grpc\Proto\Metadata|null $var)
    {
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any body = 3;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getBody()
    {
        return $this->body;
    }

    public function hasBody()
    {
        return isset($this->body);
    }

    public function clearBody()
    {
        unset($this->body);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any body = 3;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setBody(\Google\Protobuf\Any|null $var)
    {
        $this->body = $var;

        return $this;
    }

}

