<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nacos_grpc_service.proto

namespace Nacos\Grpc\GPBMetadata;

class NacosGrpcService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x8C\x04\x0A\x18nacos_grpc_service.proto\"\x83\x01\x0A\x08Metadata\x12\x0C\x0A\x04type\x18\x03 \x01(\x09\x12\x10\x0A\x08clientIp\x18\x08 \x01(\x09\x12'\x0A\x07headers\x18\x07 \x03(\x0B2\x16.Metadata.HeadersEntry\x1A.\x0A\x0CHeadersEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x09:\x028\x01\"U\x0A\x04Body\x12\x1F\x0A\x05value\x18\x02 \x03(\x0B2\x10.Body.ValueEntry\x1A,\x0A\x0AValueEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x09:\x028\x01\"J\x0A\x07Payload\x12\x1B\x0A\x08metadata\x18\x02 \x01(\x0B2\x09.Metadata\x12\"\x0A\x04body\x18\x03 \x01(\x0B2\x14.google.protobuf.Any2S\x0A\x07Request\x12\x1D\x0A\x07request\x12\x08.Payload\x1A\x08.Payload\x12)\x0A\x0FrequestBiStream\x12\x08.Payload\x1A\x08.Payload(\x010\x012<\x0A\x0FBiRequestStream\x12)\x0A\x0FrequestBiStream\x12\x08.Payload\x1A\x08.Payload(\x010\x01B,\xCA\x02\x10Nacos\\Grpc\\Proto\xE2\x02\x16Nacos\\Grpc\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

